Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,7 +3,7 @@ name: Build and Test Qt Project
 on: push
 
 jobs:
-  build:
+  build-and-test:
     name: Build and Test Qt Project
     runs-on: ubuntu-latest
 
@@ -26,11 +26,11 @@ jobs:
         run: echo "$HOME/Qt/6.7.0/gcc_64/bin" >> $GITHUB_PATH
 
       - name: Create build directory
-        run: mkdir build2
+        run: mkdir build
 
       - name: Build project
         run: |
-          cd build2
+          cd build
           export PATH="$HOME/Qt/6.7.0/gcc_64/bin:$PATH"
           qmake ../finalqmakeproject.pro  # Replace with your actual .pro file name
           make
@@ -39,18 +39,24 @@ jobs:
         run: ls -la $GITHUB_WORKSPACE
 
       - name: Verify QML test files content
-        run: cat $GITHUB_WORKSPACE/tst_userlogin.qml
+        run: cat $GITHUB_WORKSPACE/tst_userlogin.qml  # Adjust as needed
+
+      - name: Start Xvfb
+        run: Xvfb :99 -screen 0 1024x768x16 &
+
+      - name: Export DISPLAY variable
+        run: export DISPLAY=:99
 
       - name: Run QML Tests
         run: |
-         echo "Running QML Tests"
-         export DISPLAY=:99
-         for test_file in $GITHUB_WORKSPACE/tst_*.qml; do
-          echo "Running test $test_file"
-          qmltestrunner $test_file
-          if [ $? -ne 0 ]; then
-           echo "Test $test_file failed"
-           exit 1
-          fi
+          echo "Running QML Tests"
+          export QT_QPA_PLATFORM_PLUGIN_PATH="$HOME/Qt/6.7.0/gcc_64/plugins/platforms"
+          for test_file in $GITHUB_WORKSPACE/tst_*.qml; do
+            echo "Running test $test_file"
+            xvfb-run -a qmltestrunner $test_file
+            if [ $? -ne 0 ]; then
+              echo "Test $test_file failed"
+              exit 1
+            fi
           done
           echo "All tests passed"
