Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,9 +41,19 @@ jobs:
       - name: Verify QML test files content
         run: cat $GITHUB_WORKSPACE/tst_userlogin.qml
 
-      - name: Execute QML Tests
+      - name: Run QML Tests
         run: |
-          xvfb-run -s "-screen 0 1024x768x16" qmltestrunner $GITHUB_WORKSPACE/tst_userlogin.qml
-          xvfb-run -s "-screen 0 1024x768x16" qmltestrunner $GITHUB_WORKSPACE/tst_switch.qml
-          xvfb-run -s "-screen 0 1024x768x16" qmltestrunner $GITHUB_WORKSPACE/tst_register.qml
-          xvfb-run -s "-screen 0 1024x768x16" qmltestrunner $GITHUB_WORKSPACE/tst_ganeisover.qml
+          echo "Running QML Tests"
+          XVFB_DISPLAY=":99"
+          export DISPLAY=$XVFB_DISPLAY
+          Xvfb $XVFB_DISPLAY -screen 0 1024x768x16 &
+          sleep 5 # Wait for Xvfb to start
+          for test_file in $GITHUB_WORKSPACE/tst_*.qml; do
+            echo "Running test $test_file"
+            qmltestrunner $test_file
+            if [ $? -ne 0 ]; then
+              echo "Test $test_file failed"
+              exit 1
+            fi
+          done
+          echo "All tests passed"
